package sk.tuke.seregely.dipl.bug.entity;

// Generated Mar 29, 2013 7:59:27 PM by Hibernate Tools 4.0.0

/**
 * ChybaRiesitelId generated by hbm2java
 */
public class ChybaRiesitelId implements java.io.Serializable {

	private int idChyby;
	private int idRiesitela;

	public ChybaRiesitelId() {
	}

	public ChybaRiesitelId(int idChyby, int idRiesitela) {
		this.idChyby = idChyby;
		this.idRiesitela = idRiesitela;
	}

	public int getIdChyby() {
		return this.idChyby;
	}

	public void setIdChyby(int idChyby) {
		this.idChyby = idChyby;
	}

	public int getIdRiesitela() {
		return this.idRiesitela;
	}

	public void setIdRiesitela(int idRiesitela) {
		this.idRiesitela = idRiesitela;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ChybaRiesitelId))
			return false;
		ChybaRiesitelId castOther = (ChybaRiesitelId) other;

		return (this.getIdChyby() == castOther.getIdChyby())
				&& (this.getIdRiesitela() == castOther.getIdRiesitela());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdChyby();
		result = 37 * result + this.getIdRiesitela();
		return result;
	}

}
