package sk.tuke.seregely.dipl.bug.entity;

// Generated Mar 29, 2013 7:59:27 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * Chyba generated by hbm2java
 */
public class Chyba implements java.io.Serializable {

	private int idChyby;
	private Uzivatel uzivatel;
	private String popis;
	private Set chybaRiesitels = new HashSet(0);

	public Chyba() {
	}

	public Chyba(int idChyby) {
		this.idChyby = idChyby;
	}

	public Chyba(int idChyby, Uzivatel uzivatel, String popis,
			Set chybaRiesitels) {
		this.idChyby = idChyby;
		this.uzivatel = uzivatel;
		this.popis = popis;
		this.chybaRiesitels = chybaRiesitels;
	}

	public int getIdChyby() {
		return this.idChyby;
	}

	public void setIdChyby(int idChyby) {
		this.idChyby = idChyby;
	}

	public Uzivatel getUzivatel() {
		return this.uzivatel;
	}

	public void setUzivatel(Uzivatel uzivatel) {
		this.uzivatel = uzivatel;
	}

	public String getPopis() {
		return this.popis;
	}

	public void setPopis(String popis) {
		this.popis = popis;
	}

	public Set getChybaRiesitels() {
		return this.chybaRiesitels;
	}

	public void setChybaRiesitels(Set chybaRiesitels) {
		this.chybaRiesitels = chybaRiesitels;
	}

}
