package sk.tuke.seregely.dipl.bug.entity;

import java.util.HashSet;
import java.util.Set;

/**
 * Chyba generated by hbm2java
 */
public class Chyba implements java.io.Serializable {

	private int idChyby;
	private Uzivatel uzivatel;
	private String popis;
	private Set riesitels = new HashSet(0);
	private Projekt projekt;
	private CiselnikStavov ciselnikStavov;
	private Riesitel riesitel;

	public Chyba() {
	}

	public Chyba(int idChyby) {
		this.idChyby = idChyby;
	}

	public Chyba(int idChyby, Uzivatel uzivatel, String popis, Set riesitels) {
		this.idChyby = idChyby;
		this.uzivatel = uzivatel;
		this.popis = popis;
		this.riesitels = riesitels;
	}

	public int getIdChyby() {
		return this.idChyby;
	}

	public void setIdChyby(int idChyby) {
		this.idChyby = idChyby;
	}

	public Uzivatel getUzivatel() {
		return this.uzivatel;
	}

	public void setUzivatel(Uzivatel uzivatel) {
		this.uzivatel = uzivatel;
	}

	public String getPopis() {
		return this.popis;
	}

	public void setPopis(String popis) {
		this.popis = popis;
	}

	public Set getRiesitels() {
		return this.riesitels;
	}

	public void setRiesitels(Set riesitels) {
		this.riesitels = riesitels;
	}

	public Projekt getProjekt() {
		return projekt;
	}

	public void setProjekt(Projekt projekt) {
		this.projekt = projekt;
	}

	public CiselnikStavov getCiselnikStavov() {
		return ciselnikStavov;
	}

	public void setCiselnikStavov(CiselnikStavov ciselnikStavov) {
		this.ciselnikStavov = ciselnikStavov;
	}

	public Riesitel getRiesitel() {
		return riesitel;
	}

	public void setRiesitel(Riesitel riesitel) {
		this.riesitel = riesitel;
	}

}
