package sk.tuke.seregely.dipl.bug.entity;
// default package
// Generated Apr 6, 2013 9:28:57 AM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * Projekt generated by hbm2java
 */
public class Projekt implements java.io.Serializable {

	private int idProjektu;
	private String nazov;
	private String popis;
	private Set uzivatels = new HashSet(0);
	private Set<Riesitel> riesitels = new HashSet<Riesitel>(0);

	public Projekt() {
	}

	public Projekt(int idProjektu) {
		this.idProjektu = idProjektu;
	}

	public Projekt(int idProjektu, String nazov, String popis, Set uzivatels,
			Set riesitels) {
		this.idProjektu = idProjektu;
		this.nazov = nazov;
		this.popis = popis;
		this.uzivatels = uzivatels;
		this.riesitels = riesitels;
	}

	public int getIdProjektu() {
		return this.idProjektu;
	}

	public void setIdProjektu(int idProjektu) {
		this.idProjektu = idProjektu;
	}

	public String getNazov() {
		return this.nazov;
	}

	public void setNazov(String nazov) {
		this.nazov = nazov;
	}

	public String getPopis() {
		return this.popis;
	}

	public void setPopis(String popis) {
		this.popis = popis;
	}

	public Set getUzivatels() {
		return this.uzivatels;
	}

	public void setUzivatels(Set uzivatels) {
		this.uzivatels = uzivatels;
	}

	public Set getRiesitels() {
		return this.riesitels;
	}

	public void setRiesitels(Set riesitels) {
		this.riesitels = riesitels;
	}

}
