package sk.tuke.seregely.dipl.bug.entity;

// Generated Mar 29, 2013 7:59:27 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * Projekt generated by hbm2java
 */
public class Projekt implements java.io.Serializable {

	private int idProjektu;
	private String nazov;
	private String popis;
	private Set uzivatelProjekts = new HashSet(0);
	private Set projektRiesitels = new HashSet(0);

	public Projekt() {
	}

	public Projekt(int idProjektu) {
		this.idProjektu = idProjektu;
	}

	public Projekt(int idProjektu, String nazov, String popis,
			Set uzivatelProjekts, Set projektRiesitels) {
		this.idProjektu = idProjektu;
		this.nazov = nazov;
		this.popis = popis;
		this.uzivatelProjekts = uzivatelProjekts;
		this.projektRiesitels = projektRiesitels;
	}

	public int getIdProjektu() {
		return this.idProjektu;
	}

	public void setIdProjektu(int idProjektu) {
		this.idProjektu = idProjektu;
	}

	public String getNazov() {
		return this.nazov;
	}

	public void setNazov(String nazov) {
		this.nazov = nazov;
	}

	public String getPopis() {
		return this.popis;
	}

	public void setPopis(String popis) {
		this.popis = popis;
	}

	public Set getUzivatelProjekts() {
		return this.uzivatelProjekts;
	}

	public void setUzivatelProjekts(Set uzivatelProjekts) {
		this.uzivatelProjekts = uzivatelProjekts;
	}

	public Set getProjektRiesitels() {
		return this.projektRiesitels;
	}

	public void setProjektRiesitels(Set projektRiesitels) {
		this.projektRiesitels = projektRiesitels;
	}

}
