package sk.tuke.seregely.dipl.bug.entity;

// Generated Mar 29, 2013 7:59:27 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * Riesitel generated by hbm2java
 */
public class Riesitel implements java.io.Serializable {

	private int idRiesitela;
	private String celeMeno;
	private Set projektRiesitels = new HashSet(0);
	private Set vylepsenieRiesitels = new HashSet(0);
	private Set chybaRiesitels = new HashSet(0);

	public Riesitel() {
	}

	public Riesitel(int idRiesitela) {
		this.idRiesitela = idRiesitela;
	}

	public Riesitel(int idRiesitela, String celeMeno, Set projektRiesitels,
			Set vylepsenieRiesitels, Set chybaRiesitels) {
		this.idRiesitela = idRiesitela;
		this.celeMeno = celeMeno;
		this.projektRiesitels = projektRiesitels;
		this.vylepsenieRiesitels = vylepsenieRiesitels;
		this.chybaRiesitels = chybaRiesitels;
	}

	public int getIdRiesitela() {
		return this.idRiesitela;
	}

	public void setIdRiesitela(int idRiesitela) {
		this.idRiesitela = idRiesitela;
	}

	public String getCeleMeno() {
		return this.celeMeno;
	}

	public void setCeleMeno(String celeMeno) {
		this.celeMeno = celeMeno;
	}

	public Set getProjektRiesitels() {
		return this.projektRiesitels;
	}

	public void setProjektRiesitels(Set projektRiesitels) {
		this.projektRiesitels = projektRiesitels;
	}

	public Set getVylepsenieRiesitels() {
		return this.vylepsenieRiesitels;
	}

	public void setVylepsenieRiesitels(Set vylepsenieRiesitels) {
		this.vylepsenieRiesitels = vylepsenieRiesitels;
	}

	public Set getChybaRiesitels() {
		return this.chybaRiesitels;
	}

	public void setChybaRiesitels(Set chybaRiesitels) {
		this.chybaRiesitels = chybaRiesitels;
	}

}
