package sk.tuke.seregely.dipl.bug.entity;
// default package
// Generated Apr 6, 2013 9:28:57 AM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * Riesitel generated by hbm2java
 */
public class Riesitel implements java.io.Serializable {

	private int idRiesitela;
	private String celeMeno;
	private boolean veduci;
	private Set projekts = new HashSet(0);
	private Set vylepsenies = new HashSet(0);
	private Set chybas = new HashSet(0);

	public Riesitel() {
	}

	public Riesitel(int idRiesitela) {
		this.idRiesitela = idRiesitela;
	}

	public Riesitel(int idRiesitela, String celeMeno, Set projekts,
			Set vylepsenies, Set chybas) {
		this.idRiesitela = idRiesitela;
		this.celeMeno = celeMeno;
		this.projekts = projekts;
		this.vylepsenies = vylepsenies;
		this.chybas = chybas;
	}

	public int getIdRiesitela() {
		return this.idRiesitela;
	}

	public void setIdRiesitela(int idRiesitela) {
		this.idRiesitela = idRiesitela;
	}

	public String getCeleMeno() {
		return this.celeMeno;
	}

	public void setCeleMeno(String celeMeno) {
		this.celeMeno = celeMeno;
	}

	public Set getProjekts() {
		return this.projekts;
	}

	public void setProjekts(Set projekts) {
		this.projekts = projekts;
	}

	public Set getVylepsenies() {
		return this.vylepsenies;
	}

	public void setVylepsenies(Set vylepsenies) {
		this.vylepsenies = vylepsenies;
	}

	public Set getChybas() {
		return this.chybas;
	}

	public void setChybas(Set chybas) {
		this.chybas = chybas;
	}

	public boolean isVeduci() {
		return veduci;
	}

	public void setVeduci(boolean veduci) {
		this.veduci = veduci;
	}

}
