package sk.tuke.seregely.dipl.bug.entity;

// Generated Mar 29, 2013 7:59:27 PM by Hibernate Tools 4.0.0

/**
 * UzivatelProjektId generated by hbm2java
 */
public class UzivatelProjektId implements java.io.Serializable {

	private int idProjektu;
	private int idUzivatela;

	public UzivatelProjektId() {
	}

	public UzivatelProjektId(int idProjektu, int idUzivatela) {
		this.idProjektu = idProjektu;
		this.idUzivatela = idUzivatela;
	}

	public int getIdProjektu() {
		return this.idProjektu;
	}

	public void setIdProjektu(int idProjektu) {
		this.idProjektu = idProjektu;
	}

	public int getIdUzivatela() {
		return this.idUzivatela;
	}

	public void setIdUzivatela(int idUzivatela) {
		this.idUzivatela = idUzivatela;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof UzivatelProjektId))
			return false;
		UzivatelProjektId castOther = (UzivatelProjektId) other;

		return (this.getIdProjektu() == castOther.getIdProjektu())
				&& (this.getIdUzivatela() == castOther.getIdUzivatela());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdProjektu();
		result = 37 * result + this.getIdUzivatela();
		return result;
	}

}
