package sk.tuke.seregely.dipl.bug.entity;
// default package
// Generated Apr 6, 2013 9:28:57 AM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * Uzivatel generated by hbm2java
 */
public class Uzivatel implements java.io.Serializable {

	private int idUzivatela;
	private String email;
	private String celeMeno;
	private Set vylepsenies = new HashSet(0);
	private Set chybas = new HashSet(0);
	private Set projekts = new HashSet(0);

	public Uzivatel() {
	}

	public Uzivatel(int idUzivatela) {
		this.idUzivatela = idUzivatela;
	}

	public Uzivatel(int idUzivatela, String email, String celeMeno,
			Set vylepsenies, Set chybas, Set projekts) {
		this.idUzivatela = idUzivatela;
		this.email = email;
		this.celeMeno = celeMeno;
		this.vylepsenies = vylepsenies;
		this.chybas = chybas;
		this.projekts = projekts;
	}

	public int getIdUzivatela() {
		return this.idUzivatela;
	}

	public void setIdUzivatela(int idUzivatela) {
		this.idUzivatela = idUzivatela;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getCeleMeno() {
		return this.celeMeno;
	}

	public void setCeleMeno(String celeMeno) {
		this.celeMeno = celeMeno;
	}

	public Set getVylepsenies() {
		return this.vylepsenies;
	}

	public void setVylepsenies(Set vylepsenies) {
		this.vylepsenies = vylepsenies;
	}

	public Set getChybas() {
		return this.chybas;
	}

	public void setChybas(Set chybas) {
		this.chybas = chybas;
	}

	public Set getProjekts() {
		return this.projekts;
	}

	public void setProjekts(Set projekts) {
		this.projekts = projekts;
	}

}
