package sk.tuke.seregely.dipl.bug.entity;

// Generated Mar 29, 2013 7:59:27 PM by Hibernate Tools 4.0.0

/**
 * UzivatelProjekt generated by hbm2java
 */
public class UzivatelProjekt implements java.io.Serializable {

	private UzivatelProjektId id;
	private Projekt projekt;
	private Uzivatel uzivatel;

	public UzivatelProjekt() {
	}

	public UzivatelProjekt(UzivatelProjektId id, Projekt projekt,
			Uzivatel uzivatel) {
		this.id = id;
		this.projekt = projekt;
		this.uzivatel = uzivatel;
	}

	public UzivatelProjektId getId() {
		return this.id;
	}

	public void setId(UzivatelProjektId id) {
		this.id = id;
	}

	public Projekt getProjekt() {
		return this.projekt;
	}

	public void setProjekt(Projekt projekt) {
		this.projekt = projekt;
	}

	public Uzivatel getUzivatel() {
		return this.uzivatel;
	}

	public void setUzivatel(Uzivatel uzivatel) {
		this.uzivatel = uzivatel;
	}

}
