package sk.tuke.seregely.dipl.bug.entity;
// default package
// Generated Apr 6, 2013 9:28:57 AM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * Vylepsenie generated by hbm2java
 */
public class Vylepsenie implements java.io.Serializable {

	private int idVylepsenia;
	private Uzivatel uzivatel;
	private String popis;
	private Set riesitels = new HashSet(0);
	private Projekt projekt;
	private CiselnikStavov ciselnikStavov;
	private Riesitel riesitel;

	public Vylepsenie() {
	}

	public Vylepsenie(int idVylepsenia) {
		this.idVylepsenia = idVylepsenia;
	}

	public Vylepsenie(int idVylepsenia, Uzivatel uzivatel, String popis,
			Set riesitels) {
		this.idVylepsenia = idVylepsenia;
		this.uzivatel = uzivatel;
		this.popis = popis;
		this.riesitels = riesitels;
	}

	public int getIdVylepsenia() {
		return this.idVylepsenia;
	}

	public void setIdVylepsenia(int idVylepsenia) {
		this.idVylepsenia = idVylepsenia;
	}

	public Uzivatel getUzivatel() {
		return this.uzivatel;
	}

	public void setUzivatel(Uzivatel uzivatel) {
		this.uzivatel = uzivatel;
	}

	public String getPopis() {
		return this.popis;
	}

	public void setPopis(String popis) {
		this.popis = popis;
	}

	public Set getRiesitels() {
		return this.riesitels;
	}

	public void setRiesitels(Set riesitels) {
		this.riesitels = riesitels;
	}
	
	public Projekt getProjekt() {
		return projekt;
	}

	public void setProjekt(Projekt projekt) {
		this.projekt = projekt;
	}

	public CiselnikStavov getCiselnikStavov() {
		return ciselnikStavov;
	}

	public void setCiselnikStavov(CiselnikStavov ciselnikStavov) {
		this.ciselnikStavov = ciselnikStavov;
	}

	public Riesitel getRiesitel() {
		return riesitel;
	}

	public void setRiesitel(Riesitel riesitel) {
		this.riesitel = riesitel;
	}

}
