package sk.tuke.seregely.dipl.bug.entity;

// Generated Mar 29, 2013 7:59:27 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * Vylepsenie generated by hbm2java
 */
public class Vylepsenie implements java.io.Serializable {

	private int idVylepsenia;
	private Uzivatel uzivatel;
	private String popis;
	private Set vylepsenieRiesitels = new HashSet(0);

	public Vylepsenie() {
	}

	public Vylepsenie(int idVylepsenia) {
		this.idVylepsenia = idVylepsenia;
	}

	public Vylepsenie(int idVylepsenia, Uzivatel uzivatel, String popis,
			Set vylepsenieRiesitels) {
		this.idVylepsenia = idVylepsenia;
		this.uzivatel = uzivatel;
		this.popis = popis;
		this.vylepsenieRiesitels = vylepsenieRiesitels;
	}

	public int getIdVylepsenia() {
		return this.idVylepsenia;
	}

	public void setIdVylepsenia(int idVylepsenia) {
		this.idVylepsenia = idVylepsenia;
	}

	public Uzivatel getUzivatel() {
		return this.uzivatel;
	}

	public void setUzivatel(Uzivatel uzivatel) {
		this.uzivatel = uzivatel;
	}

	public String getPopis() {
		return this.popis;
	}

	public void setPopis(String popis) {
		this.popis = popis;
	}

	public Set getVylepsenieRiesitels() {
		return this.vylepsenieRiesitels;
	}

	public void setVylepsenieRiesitels(Set vylepsenieRiesitels) {
		this.vylepsenieRiesitels = vylepsenieRiesitels;
	}

}
